# Generated by Django 3.2 on 2023-12-18 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reviewproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 23, 35, 23, 297140)),
        ),
    ]
