# Generated by Django 4.2.7 on 2023-12-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_wishlist_product_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
