# Generated by Django 3.2 on 2023-12-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reviewproduct_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproduct',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
