# Generated by Django 4.2.7 on 2023-12-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.wishlist'),
            preserve_default=False,
        ),
    ]
