# Generated by Django 4.2.6 on 2023-10-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCode', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('firstName', models.TextField(blank=True, null=True)),
                ('lastName', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
