# Generated by Django 3.2 on 2023-12-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231025_1529'),
        ('book', '0002_auto_20231028_1535'),
    ]

    operations = [
    ]
